{% set name = "scikits_odes_sundials" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18c35ab2645289226ff16804db082fb91d1d31d3ee05f316d8b012accaea7032

build:
  script: 
    - export SUNDIALS_INST=$PREFIX           # [not win]
    - set "SUNDIALS_INST=%LIBRARY_PREFIX%"   # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython 
    - numpy
    - libblas
    - pip
    - sundials >=7
  run:
    - python
    - numpy
    - sundials >=7

test:
  imports:
    - numpy
    - scikits_odes_sundials
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/bmcage/odes
  summary: Sundials wrapper module for scikits.odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the SUNDIALS solvers (i.e., cvode, cvodes, ida, and idas),
    providing extra ODE and DAE solvers you can use, beyond those already in
    scipy.integrate.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - c-randall
